--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Skso-cmd/AnvilUI
build-by-default: true
branches:
- main
projects:
  AnvilUI:
    path: ""
    libFormAPI:
      - src: jojoe77777/FormAPI/FormAPI
        version: ^2.1.1
...
